name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ kernel-update ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Run initial build, and compile kernel and recovery
      - name: Build
        run: |
          sudo apt update
          sudo apt install mkbootimg bc build-essential ca-certificates cpio curl git kmod libssl-dev sudo unzip wget xz-utils -y --no-install-recommends
          # 直接从 Ubuntu 22.04 仓库下载并安装 Python 2.7
          PYTHON_VER="2.7.18-13ubuntu1.2"
          wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7-minimal_${PYTHON_VER}_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7_${PYTHON_VER}_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-minimal_${PYTHON_VER}_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-stdlib_${PYTHON_VER}_amd64.deb
          sudo dpkg -i libpython2.7-minimal_${PYTHON_VER}_amd64.deb
          sudo dpkg -i libpython2.7-stdlib_${PYTHON_VER}_amd64.deb
          sudo dpkg -i python2.7-minimal_${PYTHON_VER}_amd64.deb
          sudo dpkg -i python2.7_${PYTHON_VER}_amd64.deb
          sudo ln -sf python2.7 /usr/bin/python
          # 安装 libtinfo5
          wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb
          sudo dpkg -i libtinfo5_6.4-2_amd64.deb
          ./build.sh
      - name: Upload basic tarball with boot and recovery images
        uses: actions/upload-artifact@v4
        with:
          name: basic-tarball
          path: out/*

  flashable:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Make OTA images
        run: |
          sudo apt update
          sudo apt install -y img2simg jq sudo wget xz-utils
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ./build/fetch-and-prepare-latest-ota.sh "16.04/arm64/android9/devel" "$DEVICE" ota
          mkdir -p out/
          ./build/system-image-from-ota.sh ota/ubuntu_command out
      - uses: actions/upload-artifact@v4
        with:
          name: OTA images
          path: |
            out/boot.img
            out/system.img
            out/recovery.img
